/****** Object:  Table [dbo].[DIPProductionCondition]    Script Date: 20/10/2566 2:43:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIPProductionCondition](
	[ProductCode] [nvarchar](30) NULL,
	[S7CordStructure] [nvarchar](50) NULL,
	[S7YarnType] [nvarchar](50) NULL,
	[S71stTwist] [nvarchar](50) NULL,
	[S72ndTwist] [nvarchar](50) NULL,
	[S7ShapeOfYarn] [nvarchar](50) NULL,
	[S7Weight] [decimal](18, 3) NULL,
	[S7ProcessSettingTension] [nvarchar](50) NULL,
	[S7UseTensor] [nvarchar](50) NULL,
	[S7KnotCondition] [nvarchar](50) NULL,
	[S7SuperNylonKnot] [nvarchar](50) NULL,
	[S8DryeStretchSC] [bit] NULL,
	[S8DryeStretch] [decimal](18, 3) NULL,
	[S8DryeStretchErr] [decimal](18, 3) NULL,
	[S8DryeTempSC] [bit] NULL,
	[S8DryeTemp] [decimal](18, 3) NULL,
	[S8DryeTempErr] [decimal](18, 3) NULL,
	[S8DryePass] [decimal](18, 3) NULL,
	[S8DryeTension] [nvarchar](50) NULL,
	[S8HotStretchSC] [bit] NULL,
	[S8HotStretch] [decimal](18, 3) NULL,
	[S8HotStretchErr] [decimal](18, 3) NULL,
	[S8HotTempSC] [bit] NULL,
	[S8HotTemp] [decimal](18, 3) NULL,
	[S8HotTempErr] [decimal](18, 3) NULL,
	[S8HotPass] [decimal](18, 3) NULL,
	[S8HotTension] [nvarchar](50) NULL,
	[S8NormalStretchSC] [bit] NULL,
	[S8NormalStretch] [decimal](18, 3) NULL,
	[S8NormalStretchErr] [decimal](18, 3) NULL,
	[S8NormalTempSC] [bit] NULL,
	[S8NormalTemp] [decimal](18, 3) NULL,
	[S8NormalTempErr] [decimal](18, 3) NULL,
	[S8NormalPass] [decimal](18, 3) NULL,
	[S8NormalTension] [nvarchar](50) NULL,
	[S8TotalStretchSC] [bit] NULL,
	[S8TotalStretch] [decimal](18, 3) NULL,
	[S8TotalStretchErr] [decimal](18, 3) NULL,
	[S8TotalTempSC] [bit] NULL,
	[S8TotalTemp] [decimal](18, 3) NULL,
	[S8TotalTempErr] [decimal](18, 3) NULL,
	[S8TotalPass] [decimal](18, 3) NULL,
	[S8TotalTension] [nvarchar](50) NULL,
	[S8SpeedSC] [bit] NULL,
	[S8Speed] [decimal](18, 3) NULL,
	[S8SpeedErr] [decimal](18, 3) NULL,
	[S8NoOfCordsOfProcessing] [decimal](18, 3) NULL,
	[S8NoOfCordsOfProcessingErr] [decimal](18, 3) NULL,
	[S8Sofnor] [nvarchar](50) NULL,
	[S8DrawNip] [nvarchar](50) NULL,
	[S8Concentration] [nvarchar](50) NULL,
	[S8NipRollerPressureNo1Front] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo1FrontErr] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo2Front] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo2FrontErr] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo1Back] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo1BackErr] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo2Back] [decimal](18, 3) NULL,
	[S8NipRollerPressureNo2BackErr] [decimal](18, 3) NULL,
	[S8WPUStandardNo1] [decimal](18, 3) NULL,
	[S8WPUStandardNo1Err] [decimal](18, 3) NULL,
	[S8WPUStandardNo2] [decimal](18, 3) NULL,
	[S8WPUStandardNo2Err] [decimal](18, 3) NULL,
	[S9ContactPressureUp] [bit] NULL,
	[S9ContactPressureDown] [bit] NULL,
	[S9ContactPressure] [nvarchar](50) NULL,
	[S9BaseWindGear] [decimal](18, 3) NULL,
	[S9TraverseGuideSizeLrage] [bit] NULL,
	[S9TraverseGuideSizeSmall] [bit] NULL,
	[S9TraverseGuideSize] [nvarchar](50) NULL,
	[S9WindVoltageSet] [decimal](18, 3) NULL,
	[S9WindVoltageSetErr] [decimal](18, 3) NULL,
	[S9AyameDaial] [decimal](18, 6) NULL,
	[S9AyameDaialErr] [decimal](18, 6) NULL,
	[S9TensionSpringLrage] [bit] NULL,
	[S9TensionSpringSmall] [bit] NULL,
	[S9TensionSpring] [nvarchar](50) NULL,
	[S9TensionWind] [nvarchar](50) NULL,
	[S9PackingStandard] [decimal](18, 3) NULL,
	[S9PackingStandardErr] [decimal](18, 3) NULL,
	[S9TubeColor] [nvarchar](50) NULL,
	[S9Tail] [nvarchar](50) NULL,
	[S9CounterSetting] [decimal](18, 3) NULL,
	[S9CounterSettingErr] [decimal](18, 3) NULL,
	[S9CheeseWeight] [decimal](18, 3) NULL,
	[S9CheeseWeightErr] [decimal](18, 3) NULL,
	[S9HowToStartProductionEng] [nvarchar](100) NULL,
	[S9HowToStartProductionTh] [nvarchar](100) NULL,
	[S9Rewind] [nvarchar](100) NULL,
	[S9Package] [nvarchar](100) NULL,
	[S9Sampling] [nvarchar](100) NULL
) ON [PRIMARY]

GO
