ALTER TABLE S8WetPickup ALTER COLUMN AMV1 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMV2 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMV3 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMV4 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMAmp1 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMAmp2 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMAmp3 nvarchar(50)
GO

ALTER TABLE S8WetPickup ALTER COLUMN AMAmp4 nvarchar(50)
GO
