/****** Object:  StoredProcedure [dbo].[SaveS4x2Condition]    Script Date: 10/15/2023 12:47:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author: Chumpon Asaneerat
-- Description:	SaveS4x2Condition
-- [== History ==]
-- <2022-08-20> :
--	- Stored Procedure Created.
--
-- [== Example ==]
--
-- 
-- =============================================
CREATE PROCEDURE [dbo].[SaveS4x2Condition] (
    @PCTwist1Id int,
    @ProductCode nvarchar (30),
	@FullPackageModeSC bit ,
	@FullPackageMode nvarchar (100),
	@FullPackageModeActual nvarchar (100),
	@LengthSC bit ,
	@Length decimal (18, 3),
	@LengthErr decimal (18, 3),
	@LengthActual decimal (18, 3),
	@WindAngleShiftFunctionSC bit ,
	@WindAngleShiftFunction nvarchar (100),
	@WindAngleShiftFunctionActual nvarchar (100),
	@AmountOfDisturbSC bit ,
	@AmountOfDisturb nvarchar (100),
	@AmountOfDisturbActual nvarchar (100),
	@WindAngleSC bit ,
	@WindAngle decimal (18, 3),
	@WindAngleActual decimal (18, 3),
	@DistuebAccelerationTimeSC bit ,
	@DistuebAccelerationTime decimal (18, 3),
	@DistuebAccelerationTimeActual decimal (18, 3),
	@DistuebDccelerationTimeSC bit ,
	@DistuebDccelerationTime decimal (18, 3),
	@DistuebDccelerationTimeActual decimal (18, 3),
	@TensorSettingSC bit ,
	@TensorSetting nvarchar (100),
	@TensorSettingActual nvarchar (100),
	@FeedRollerSettingSC bit ,
	@FeedRollerSetting nvarchar (100),
	@FeedRollerSettingActual nvarchar (100),
	@BollonSettingSC bit ,
	@BollonSetting nvarchar (100),
	@BollonSettingActual nvarchar (100),
	@MethodOfKnotSC bit ,
	@MethodOfKnot nvarchar (100),
	@MethodOfKnotActual nvarchar (100),
	@WindQuantitySC bit ,
	@WindQuantity decimal (18, 3),
	@WindQuantityErr decimal (18, 3),
	@WindQuantityActual decimal (18, 3),
	@DoffTimeSC bit ,
	@DoffTime decimal (18, 3),
	@DoffTimeErr decimal (18, 3),
	@DoffTimeActual decimal (18, 3),
	@ProductQuantitySC bit ,
	@ProductQuantityKg decimal (18, 3),
	@ProductQuantityKgActual decimal (18, 3),
	@ProductQuantityDay decimal (18, 3),
	@ProductQuantityDayActual decimal (18, 3),
	@CalculatedTwistingNumberSC bit ,
	@CalculatedTwistingNumber decimal (18, 3),
	@CalculatedTwistingNumberErr decimal (18, 3),
	@CalculatedTwistingNumberActual decimal (18, 3),
	@NumberOfSpindleRotationSC bit ,
	@NumberOfSpindleRotation decimal (18, 3),
	@NumberOfSpindleRotationErr decimal (18, 3),
	@NumberOfSpindleRotationActual decimal (18, 3),
	@YarnSpeedSC bit ,
	@YarnSpeed decimal (18, 3),
	@YarnSpeedErr decimal (18, 3),
	@YarnSpeedActual decimal (18, 3),
	@SpecialMentionSC bit ,
	@SpecialMention nvarchar (100),
	@SpecialMentionActual nvarchar (100) , 
    @UpdateBy nvarchar(100) , 
    @S4x2ConditionId int = NULL out
, @errNum as int = 0 out
, @errMsg as nvarchar(MAX) = N'' out)
AS
BEGIN
	BEGIN TRY
        IF EXISTS (SELECT TOP 1 * FROM S4x2Condition WHERE S4x2ConditionId = @S4x2ConditionId)
        BEGIN
            UPDATE S4x2Condition
               SET  PCTwist1Id = @PCTwist1Id ,
                    ProductCode = @ProductCode ,
                    FullPackageModeSC = @FullPackageModeSC ,
                    FullPackageMode = @FullPackageMode ,
                    FullPackageModeActual = @FullPackageModeActual ,
                    LengthSC = @LengthSC ,
                    [Length] = @Length ,
                    LengthErr = @LengthErr ,
                    LengthActual = @LengthActual ,
                    WindAngleShiftFunctionSC = @WindAngleShiftFunctionSC ,
                    WindAngleShiftFunction = @WindAngleShiftFunction ,
                    WindAngleShiftFunctionActual = @WindAngleShiftFunctionActual ,
                    AmountOfDisturbSC = @AmountOfDisturbSC ,
                    AmountOfDisturb = @AmountOfDisturb ,
                    AmountOfDisturbActual = @AmountOfDisturbActual ,
                    WindAngleSC = @WindAngleSC ,
                    WindAngle = @WindAngle ,
                    WindAngleActual = @WindAngleActual ,
                    DistuebAccelerationTimeSC = @DistuebAccelerationTimeSC ,
                    DistuebAccelerationTime = @DistuebAccelerationTime ,
                    DistuebAccelerationTimeActual = @DistuebAccelerationTimeActual ,
                    DistuebDccelerationTimeSC = @DistuebDccelerationTimeSC ,
                    DistuebDccelerationTime = @DistuebDccelerationTime ,
                    DistuebDccelerationTimeActual = @DistuebDccelerationTimeActual ,
                    TensorSettingSC = @TensorSettingSC ,
                    TensorSetting = @TensorSetting ,
                    TensorSettingActual = @TensorSettingActual ,
                    FeedRollerSettingSC = @FeedRollerSettingSC ,
                    FeedRollerSetting = @FeedRollerSetting ,
                    FeedRollerSettingActual = @FeedRollerSettingActual ,
                    BollonSettingSC = @BollonSettingSC ,
                    BollonSetting = @BollonSetting ,
                    BollonSettingActual = @BollonSettingActual ,
                    MethodOfKnotSC = @MethodOfKnotSC ,
                    MethodOfKnot = @MethodOfKnot ,
                    MethodOfKnotActual = @MethodOfKnotActual ,
                    WindQuantitySC = @WindQuantitySC ,
                    WindQuantity = @WindQuantity ,
                    WindQuantityErr = @WindQuantityErr ,
                    WindQuantityActual = @WindQuantityActual ,
                    DoffTimeSC = @DoffTimeSC ,
                    DoffTime = @DoffTime ,
                    DoffTimeErr = @DoffTimeErr ,
                    DoffTimeActual = @DoffTimeActual ,
                    ProductQuantitySC = @ProductQuantitySC ,
                    ProductQuantityKg = @ProductQuantityKg ,
                    ProductQuantityKgActual = @ProductQuantityKgActual ,
                    ProductQuantityDay = @ProductQuantityDay ,
                    ProductQuantityDayActual = @ProductQuantityDayActual ,
                    CalculatedTwistingNumberSC = @CalculatedTwistingNumberSC ,
                    CalculatedTwistingNumber = @CalculatedTwistingNumber ,
                    CalculatedTwistingNumberErr = @CalculatedTwistingNumberErr ,
                    CalculatedTwistingNumberActual = @CalculatedTwistingNumberActual ,
                    NumberOfSpindleRotationSC = @NumberOfSpindleRotationSC ,
                    NumberOfSpindleRotation = @NumberOfSpindleRotation ,
                    NumberOfSpindleRotationErr = @NumberOfSpindleRotationErr ,
                    NumberOfSpindleRotationActual = @NumberOfSpindleRotationActual ,
                    YarnSpeedSC = @YarnSpeedSC ,
                    YarnSpeed = @YarnSpeed ,
                    YarnSpeedErr = @YarnSpeedErr ,
                    YarnSpeedActual = @YarnSpeedActual ,
                    SpecialMentionSC = @SpecialMentionSC ,
                    SpecialMention = @SpecialMention ,
                    SpecialMentionActual = @SpecialMentionActual,
                    UpdateBy = @UpdateBy ,
                    UpdateDate = GETDATE()
             WHERE S4x2ConditionId = @S4x2ConditionId
        END
        ELSE
        BEGIN
			INSERT INTO S4x2Condition
		    (
                PCTwist1Id, 
                ProductCode,
				FullPackageModeSC,
				FullPackageMode,
				FullPackageModeActual,
				LengthSC,
				[Length],
				LengthErr,
				LengthActual,
				WindAngleShiftFunctionSC,
				WindAngleShiftFunction,
				WindAngleShiftFunctionActual,
				AmountOfDisturbSC,
				AmountOfDisturb,
				AmountOfDisturbActual,
				WindAngleSC,
				WindAngle,
				WindAngleActual,
				DistuebAccelerationTimeSC,
				DistuebAccelerationTime,
				DistuebAccelerationTimeActual,
				DistuebDccelerationTimeSC,
				DistuebDccelerationTime,
				DistuebDccelerationTimeActual,
				TensorSettingSC,
				TensorSetting,
				TensorSettingActual,
				FeedRollerSettingSC,
				FeedRollerSetting,
				FeedRollerSettingActual,
				BollonSettingSC,
				BollonSetting,
				BollonSettingActual,
				MethodOfKnotSC,
				MethodOfKnot,
				MethodOfKnotActual,
				WindQuantitySC,
				WindQuantity,
				WindQuantityErr,
				WindQuantityActual,
				DoffTimeSC,
				DoffTime,
				DoffTimeErr,
				DoffTimeActual,
				ProductQuantitySC,
				ProductQuantityKg,
				ProductQuantityKgActual,
				ProductQuantityDay,
				ProductQuantityDayActual,
				CalculatedTwistingNumberSC,
				CalculatedTwistingNumber,
				CalculatedTwistingNumberErr,
				CalculatedTwistingNumberActual,
				NumberOfSpindleRotationSC,
				NumberOfSpindleRotation,
				NumberOfSpindleRotationErr,
				NumberOfSpindleRotationActual,
				YarnSpeedSC,
				YarnSpeed,
				YarnSpeedErr,
				YarnSpeedActual,
				SpecialMentionSC,
				SpecialMention,
				SpecialMentionActual ,
                UpdateBy ,
                UpdateDate
			)
			VALUES
			(
                @PCTwist1Id ,
                @ProductCode ,
				@FullPackageModeSC  ,
				@FullPackageMode ,
				@FullPackageModeActual ,
				@LengthSC  ,
				@Length ,
				@LengthErr ,
				@LengthActual ,
				@WindAngleShiftFunctionSC  ,
				@WindAngleShiftFunction ,
				@WindAngleShiftFunctionActual ,
				@AmountOfDisturbSC  ,
				@AmountOfDisturb ,
				@AmountOfDisturbActual ,
				@WindAngleSC  ,
				@WindAngle ,
				@WindAngleActual ,
				@DistuebAccelerationTimeSC  ,
				@DistuebAccelerationTime ,
				@DistuebAccelerationTimeActual ,
				@DistuebDccelerationTimeSC  ,
				@DistuebDccelerationTime ,
				@DistuebDccelerationTimeActual ,
				@TensorSettingSC  ,
				@TensorSetting ,
				@TensorSettingActual ,
				@FeedRollerSettingSC  ,
				@FeedRollerSetting ,
				@FeedRollerSettingActual ,
				@BollonSettingSC  ,
				@BollonSetting ,
				@BollonSettingActual ,
				@MethodOfKnotSC  ,
				@MethodOfKnot ,
				@MethodOfKnotActual ,
				@WindQuantitySC  ,
				@WindQuantity ,
				@WindQuantityErr ,
				@WindQuantityActual ,
				@DoffTimeSC  ,
				@DoffTime ,
				@DoffTimeErr ,
				@DoffTimeActual ,
				@ProductQuantitySC  ,
				@ProductQuantityKg ,
				@ProductQuantityKgActual ,
				@ProductQuantityDay ,
				@ProductQuantityDayActual ,
				@CalculatedTwistingNumberSC  ,
				@CalculatedTwistingNumber ,
				@CalculatedTwistingNumberErr ,
				@CalculatedTwistingNumberActual ,
				@NumberOfSpindleRotationSC  ,
				@NumberOfSpindleRotation ,
				@NumberOfSpindleRotationErr ,
				@NumberOfSpindleRotationActual ,
				@YarnSpeedSC  ,
				@YarnSpeed ,
				@YarnSpeedErr ,
				@YarnSpeedActual ,
				@SpecialMentionSC  ,
				@SpecialMention ,
				@SpecialMentionActual ,
                @UpdateBy ,
                GETDATE()
			);
        END

        SET @S4x2ConditionId = @@IDENTITY;

        -- Update Error Status/Message
        SET @errNum = 0;
        SET @errMsg = 'Success';
	END TRY
	BEGIN CATCH
		SET @errNum = ERROR_NUMBER();
		SET @errMsg = ERROR_MESSAGE();
	END CATCH
END

GO
