/****** Object:  Table [dbo].[DIPConditionStd]    Script Date: 23/10/2566 1:44:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIPConditionStd](
	[ProductCode] [nvarchar](30) NULL,
	[S7YarnCordStructureSC] [bit] NULL,
	[S7YarnCordStructureSet] [nvarchar](50) NULL,
	[S7YarnCordStructureSet2] [nvarchar](50) NULL,
	[S7YarnYarnTypeSC] [bit] NULL,
	[S7YarnYarnTypeSet] [nvarchar](50) NULL,
	[S7YarnYarnTypeSet2] [nvarchar](50) NULL,
	[S7Yarn1stTwistSC] [bit] NULL,
	[S7Yarn1stTwistSet] [nvarchar](50) NULL,
	[S7Yarn1stTwistSet2] [nvarchar](50) NULL,
	[S7Yarn2ndTwistSC] [bit] NULL,
	[S7Yarn2ndTwistSet] [nvarchar](50) NULL,
	[S7Yarn2ndTwistSet2] [nvarchar](50) NULL,
	[S7YarnLabelOfYarnSC] [bit] NULL,
	[S7YarnLabelOfYarnSet] [nvarchar](50) NULL,
	[S7YarnLabelOfYarnSet2] [nvarchar](50) NULL,
	[S7YarnWeightSC] [bit] NULL,
	[S7YarnWeightSet] [decimal](18, 3) NULL,
	[S7YarnWeightSetErr] [decimal](18, 3) NULL,
	[S7YarnWeightSet2] [decimal](18, 3) NULL,
	[S7YarnWeightSetErr2] [decimal](18, 3) NULL,
	[S7CreelSettingUseTensorSC] [bit] NULL,
	[S7CreelSettingUseTensorSet] [nvarchar](50) NULL,
	[S7CreelSettingUseTensorSet2] [nvarchar](50) NULL,
	[S7CreelSettingKnotConditionSC] [bit] NULL,
	[S7CreelSettingKnotConditionSet] [decimal](18, 3) NULL,
	[S7CreelSettingKnotConditionSet2] [decimal](18, 3) NULL,
	[S7CreelSettingSlubCatsweSC] [bit] NULL,
	[S7CreelSettingSlubCatsweSet] [decimal](18, 3) NULL,
	[S7CreelSettingSlubCatsweSet2] [decimal](18, 3) NULL,
	[S8StretchDryerSC] [bit] NULL,
	[S8StretchDryerSet] [decimal](18, 3) NULL,
	[S8StretchDryerSetErr] [decimal](18, 3) NULL,
	[S8StretchDryerSet2] [decimal](18, 3) NULL,
	[S8StretchDryerSetErr2] [decimal](18, 3) NULL,
	[S8StretchStretchHotSC] [bit] NULL,
	[S8StretchStretchHotSet] [decimal](18, 3) NULL,
	[S8StretchStretchHotSetErr] [decimal](18, 3) NULL,
	[S8StretchHotSet2] [decimal](18, 3) NULL,
	[S8StretchHotSetErr2] [decimal](18, 3) NULL,
	[S8StretchNormalSC] [bit] NULL,
	[S8StretchNormalSet] [decimal](18, 3) NULL,
	[S8StretchNormalSetErr] [decimal](18, 3) NULL,
	[S8StretchNormalSet2] [decimal](18, 3) NULL,
	[S8StretchNormalSetErr2] [decimal](18, 3) NULL,
	[S8StretchTotalSC] [bit] NULL,
	[S8StretchTotalSet] [decimal](18, 3) NULL,
	[S8StretchTotalSetErr] [decimal](18, 3) NULL,
	[S8StretchTotalSet2] [decimal](18, 3) NULL,
	[S8StretchTotalSetErr2] [decimal](18, 3) NULL,
	[S8TempDryerSC] [bit] NULL,
	[S8TempDryerSet] [decimal](18, 3) NULL,
	[S8TempDryerSetErr] [decimal](18, 3) NULL,
	[S8TempDryerSet2] [decimal](18, 3) NULL,
	[S8TempDryerSetErr2] [decimal](18, 3) NULL,
	[S8TempHotSC] [bit] NULL,
	[S8TempHotSet] [decimal](18, 3) NULL,
	[S8TempHotSetErr] [decimal](18, 3) NULL,
	[S8TempHotSet2] [decimal](18, 3) NULL,
	[S8TempHotSetErr2] [decimal](18, 3) NULL,
	[S8TempNormalSC] [bit] NULL,
	[S8TempNormalSet] [decimal](18, 3) NULL,
	[S8TempNormalSetErr] [decimal](18, 3) NULL,
	[S8TempNormalSet2] [decimal](18, 3) NULL,
	[S8TempNormalSetErr2] [decimal](18, 3) NULL,
	[S8CounterSettingSC] [bit] NULL,
	[S8CounterSettingSet] [nvarchar](50) NULL,
	[S8CounterSettingSet2] [nvarchar](50) NULL,
	[S8SpeedSC] [bit] NULL,
	[S8SpeedSet] [decimal](18, 3) NULL,
	[S8SpeedErr] [decimal](18, 3) NULL,
	[S8SpeedSet2] [decimal](18, 3) NULL,
	[S8SpeedSetErr2] [decimal](18, 3) NULL,
	[S8NoOfCordsSC] [bit] NULL,
	[S8NoOfCordsSet] [decimal](18, 3) NULL,
	[S8NoOfCordsSet2] [decimal](18, 3) NULL,
	[S8SofnorSC] [bit] NULL,
	[S8SofnorSet] [nvarchar](50) NULL,
	[S8SofnorSet2] [nvarchar](50) NULL,
	[S8DrawNipSC] [bit] NULL,
	[S8DrawNipSet] [decimal](18, 3) NULL,
	[S8DrawNipSet2] [decimal](18, 3) NULL,
	[S8DippingNo1ConcentrationSC] [bit] NULL,
	[S8DippingNo1ConcentrationSet] [nvarchar](50) NULL,
	[S8DippingNo1ConcentrationSet2] [nvarchar](50) NULL,
	[S8DippingNo1NipFrontSC] [bit] NULL,
	[S8DippingNo1NipFrontSet] [nvarchar](50) NULL,
	[S8DippingNo1NipFrontSet2] [nvarchar](50) NULL,
	[S8DippingNo1NipBackSC] [bit] NULL,
	[S8DippingNo1NipBackSet] [nvarchar](50) NULL,
	[S8DippingNo1NipBackSet2] [nvarchar](50) NULL,
	[S8DippingNo1WPUstdSC] [bit] NULL,
	[S8DippingNo1WPUstdSet] [nvarchar](50) NULL,
	[S8DippingNo1WPUstdSet2] [nvarchar](50) NULL,
	[S8DippingNo2ConcentrationSC] [bit] NULL,
	[S8DippingNo2ConcentrationSet] [nvarchar](50) NULL,
	[S8DippingNo2ConcentrationSet2] [nvarchar](50) NULL,
	[S8DippingNo2NipFrontSC] [bit] NULL,
	[S8DippingNo2NipFrontSet] [nvarchar](50) NULL,
	[S8DippingNo2NipFrontSet2] [nvarchar](50) NULL,
	[S8DippingNo2NipBackSC] [bit] NULL,
	[S8DippingNo2NipBackSet] [nvarchar](50) NULL,
	[S8DippingNo2NipBackSet2] [nvarchar](50) NULL,
	[S8DippingNo2WPUstdSC] [bit] NULL,
	[S8DippingNo2WPUstdSet] [nvarchar](50) NULL,
	[S8DippingNo2WPUstdSet2] [nvarchar](50) NULL,
	[S9WinderAyameDaialSC] [bit] NULL,
	[S9WinderAyameDaialSet] [decimal](18, 6) NULL,
	[S9WinderAyameDaialSet2] [decimal](18, 6) NULL,
	[S9WinderMpaSC] [bit] NULL,
	[S9WinderMpaSet] [decimal](18, 3) NULL,
	[S9WinderMpaSet2] [decimal](18, 3) NULL,
	[S9WinderSpringSC] [bit] NULL,
	[S9WinderSpringSet] [decimal](18, 3) NULL,
	[S9WinderSpringSet2] [decimal](18, 3) NULL,
	[S9WinderPeperTubeColorSC] [bit] NULL,
	[S9WinderPeperTubeColorSet] [nvarchar](50) NULL,
	[S9WinderPeperTubeColorSet2] [nvarchar](50) NULL,
	[S9WinderCheeseWeightSC] [bit] NULL,
	[S9WinderCheeseWeightSet] [nvarchar](50) NULL,
	[S9WinderCheeseWeightSet2] [nvarchar](50) NULL,
	[S9ExhaustFanOven1CirculatingFanSC] [bit] NULL,
	[S9ExhaustFanOven1CirculatingFanSet] [decimal](18, 3) NULL,
	[S9ExhaustFanOven1CirculatingFanSet2] [decimal](18, 3) NULL,
	[S9ExhaustFanOven2CirculatingFanSC] [bit] NULL,
	[S9ExhaustFanOven2CirculatingFanSet] [decimal](18, 3) NULL,
	[S9ExhaustFanOven2CirculatingFanSet2] [decimal](18, 3) NULL,
	[S9ExhaustFanOven1ExhaustFanSC] [bit] NULL,
	[S9ExhaustFanOven1ExhaustFanSet] [decimal](18, 3) NULL,
	[S9ExhaustFanOven1ExhaustFanSet2] [decimal](18, 3) NULL,
	[S9ExhaustFanOven2ExhaustFanSC] [bit] NULL,
	[S9ExhaustFanOven2ExhaustFanSet] [decimal](18, 3) NULL,
	[S9ExhaustFanOven2ExhaustFanSet2] [decimal](18, 3) NULL,
	[S9ExhaustFanOvenFrontExhaustFanSC] [bit] NULL,
	[S9ExhaustFanOvenFrontExhaustFanSet] [decimal](18, 3) NULL,
	[S9ExhaustFanOvenFrontExhaustFanSet2] [decimal](18, 3) NULL,
	[S9ExhaustFanOvenBackExhaustFanSC] [bit] NULL,
	[S9ExhaustFanOvenBackExhaustFanSet] [decimal](18, 3) NULL,
	[S9ExhaustFanOvenBackExhaustFanSet2] [decimal](18, 3) NULL,
	[S9SpongSC] [bit] NULL,
	[S9SpongSet] [nvarchar](50) NULL,
	[S9SpongSet2] [nvarchar](50) NULL
) ON [PRIMARY]

GO
