/****** Object:  StoredProcedure [dbo].[SaveCordSamplingDetails]    Script Date: 1/26/2024 3:43:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author: Chumpon Asaneerat
-- Description:	SaveCordSamplingDetails
-- [== History ==]
-- <2022-08-20> :
--	- Stored Procedure Created.
--
-- [== Example ==]
--
-- 
-- =============================================
ALTER PROCEDURE [dbo].[SaveCordSamplingDetails] (
	@SamplingDate datetime ,
  	@TwistYarn bit ,
	@CordDipping bit ,
	@Rawmaterial bit ,
	@CustomerName nvarchar (100) ,
	@ProductCode nvarchar (30) ,
	@CordStructure nvarchar (100) ,
	@LotNo nvarchar (50) ,
	@ProductionSituationTwisting bit ,
	@ProductionSituationHeatSet bit ,
	@ProductionSituationDipCord bit ,
	@ProductionSituationJointing bit ,
	@StandardOfTwisting nvarchar (100) ,
	@MCCode nvarchar(10) ,
	@Bobbin bit ,
	@Cheese bit ,
	@TaperBB bit,
	@ContainerOthers bit,
	@SpindleNo nvarchar (100) ,
	@Quantity nvarchar (100) ,
	@Polyester bit,
	@Nylon66 bit,
	@MaterialOthers bit,
	@YarnType nvarchar (100) ,
	@Process bit,
	@Product bit,
	@Special bit,
	@Trial bit,
	@Shift nvarchar (50) ,
	@ShiftName nvarchar (100) ,
	@Remark nvarchar (100) ,
	@Sender nvarchar (100) ,
	@SenderTime datetime ,
	@Direct bit,
	@Relax bit,
	@Relax_k nvarchar (50) ,
	@Relax_n nvarchar (50) ,
	@Necessary bit,
	@NotNecessary bit,
	@SpecialMentionJointing bit,
	@SpecialMentionNoJointing bit,
	@TensileR1 decimal (18, 3) ,
	@TensileL1 decimal (18, 3) ,
	@TensileR2 decimal (18, 3) ,
	@TensileL2 decimal (18, 3) ,
	@TensileR3 decimal (18, 3) ,
	@TensileL3 decimal (18, 3) ,
	@TensileR4 decimal (18, 3) ,
	@TensileL4 decimal (18, 3) ,
	@TensileR5 decimal (18, 3) ,
	@TensileL5 decimal (18, 3) ,
	@TensileRSum decimal (18, 3) ,
	@TensileLSum decimal (18, 3) ,
	@FirstTwistingR1 decimal (18, 3) ,
	@FirstTwistingL1 decimal (18, 3) ,
	@FirstTwistingR2 decimal (18, 3) ,
	@FirstTwistingL2 decimal (18, 3) ,
	@FirstTwistingR3 decimal (18, 3) ,
	@FirstTwistingL3 decimal (18, 3) ,
	@FirstTwistingR4 decimal (18, 3) ,
	@FirstTwistingL4 decimal (18, 3) ,
	@FirstTwistingR5 decimal (18, 3) ,
	@FirstTwistingL5 decimal (18, 3) ,
	@FirstTwistingRSum decimal (18, 3) ,
	@FirstTwistingLSum decimal (18, 3) ,
	@SecondTwistingR1 decimal (18, 3) ,
	@SecondTwistingL1 decimal (18, 3) ,
	@SecondTwistingR2 decimal (18, 3) ,
	@SecondTwistingL2 decimal (18, 3) ,
	@SecondTwistingR3 decimal (18, 3) ,
	@SecondTwistingL3 decimal (18, 3) ,
	@SecondTwistingR4 decimal (18, 3) ,
	@SecondTwistingL4 decimal (18, 3) ,
	@SecondTwistingR5 decimal (18, 3) ,
	@SecondTwistingL5 decimal (18, 3) ,
	@SecondTwistingRSum decimal (18, 3) ,
	@SecondTwistingLSum decimal (18, 3) ,
	@Remark1 nvarchar (100) ,
	@Remark2 nvarchar (100) ,
	@Remark3 nvarchar (100) ,
	@Remark4 nvarchar (100) ,
	@Remark5 nvarchar (100) ,
	@RemarkSum nvarchar (100) ,
	@RemarkOther nvarchar(max) ,
	@Tester nvarchar (100) ,
	@TesterTime datetime ,
	@TestResult bit ,
	@SamplingId int = NULL out
, @errNum as int = 0 out
, @errMsg as nvarchar(MAX) = N'' out)
AS
BEGIN
	BEGIN TRY
        IF EXISTS (SELECT TOP 1 * FROM CordSamplingDetails WHERE SamplingId = @SamplingId)
        BEGIN
            UPDATE CordSamplingDetails 
               SET 	TwistYarn = @TwistYarn ,
					CordDipping = @CordDipping ,
					Rawmaterial = @Rawmaterial ,
					SamplingDate = @SamplingDate ,
					CustomerName = @CustomerName ,
					ProductCode = @ProductCode ,
					CordStructure = @CordStructure ,
					LotNo = @LotNo ,
					ProductionSituationTwisting = @ProductionSituationTwisting ,
					ProductionSituationHeatSet = @ProductionSituationHeatSet ,
					ProductionSituationDipCord = @ProductionSituationDipCord ,
					ProductionSituationJointing = @ProductionSituationJointing ,
					StandardOfTwisting = @StandardOfTwisting ,
					MCCode = @MCCode ,
					Bobbin = @Bobbin ,
					Cheese = @Cheese ,
					TaperBB = @TaperBB ,
					ContainerOthers = @ContainerOthers ,
					SpindleNo = @SpindleNo ,
					Quantity = @Quantity ,
					Polyester = @Polyester ,
					Nylon66 = @Nylon66 ,
					MaterialOthers = @MaterialOthers ,
					YarnType = @YarnType ,
					Process = @Process ,
					Product = @Product ,
					Special = @Special ,
					Trial = @Trial ,
					[Shift] = @Shift ,
					ShiftName = @ShiftName ,
					Remark = @Remark ,
					Sender = @Sender ,
					SenderTime = @SenderTime ,
					Direct = @Direct ,
					Relax = @Relax ,
					Relax_k = @Relax_k ,
					Relax_n = @Relax_n ,
					Necessary = @Necessary ,
					NotNecessary = @NotNecessary ,
					SpecialMentionJointing = @SpecialMentionJointing ,
					SpecialMentionNoJointing = @SpecialMentionNoJointing ,
					TensileR1 = @TensileR1 ,
					TensileL1 = @TensileL1 ,
					TensileR2 = @TensileR2 ,
					TensileL2 = @TensileL2 ,
					TensileR3 = @TensileR3 ,
					TensileL3 = @TensileL3 ,
					TensileR4 = @TensileR4 ,
					TensileL4 = @TensileL4 ,
					TensileR5 = @TensileR5 ,
					TensileL5 = @TensileL5 ,
					TensileRSum = @TensileRSum ,
					TensileLSum = @TensileLSum ,
					FirstTwistingR1 = @FirstTwistingR1 ,
					FirstTwistingL1 = @FirstTwistingL1 ,
					FirstTwistingR2 = @FirstTwistingR2 ,
					FirstTwistingL2 = @FirstTwistingL2 ,
					FirstTwistingR3 = @FirstTwistingR3 ,
					FirstTwistingL3 = @FirstTwistingL3 ,
					FirstTwistingR4 = @FirstTwistingR4 ,
					FirstTwistingL4 = @FirstTwistingL4 ,
					FirstTwistingR5 = @FirstTwistingR5 ,
					FirstTwistingL5 = @FirstTwistingL5 ,
					FirstTwistingRSum = @FirstTwistingRSum ,
					FirstTwistingLSum = @FirstTwistingLSum ,
					SecondTwistingR1 = @SecondTwistingR1 ,
					SecondTwistingL1 = @SecondTwistingL1 ,
					SecondTwistingR2 = @SecondTwistingR2 ,
					SecondTwistingL2 = @SecondTwistingL2 ,
					SecondTwistingR3 = @SecondTwistingR3 ,
					SecondTwistingL3 = @SecondTwistingL3 ,
					SecondTwistingR4 = @SecondTwistingR4 ,
					SecondTwistingL4 = @SecondTwistingL4 ,
					SecondTwistingR5 = @SecondTwistingR5 ,
					SecondTwistingL5 = @SecondTwistingL5 ,
					SecondTwistingRSum = @SecondTwistingRSum ,
					SecondTwistingLSum = @SecondTwistingLSum ,
					Remark1 = @Remark1 ,
					Remark2 = @Remark2 ,
					Remark3 = @Remark3 ,
					Remark4 = @Remark4 ,
					Remark5 = @Remark5 ,
					RemarkSum = @RemarkSum ,
					RemarkOther = @RemarkOther ,
					Tester = @Tester ,
					TesterTime = @TesterTime ,
					TestResult = @TestResult
             WHERE SamplingId = @SamplingId
        END
        ELSE
        BEGIN
			INSERT INTO CordSamplingDetails
		    (
                TwistYarn ,
				CordDipping ,
				Rawmaterial ,
				SamplingDate ,
				CustomerName ,
				ProductCode ,
				CordStructure ,
				LotNo ,
				ProductionSituationTwisting ,
				ProductionSituationHeatSet ,
				ProductionSituationDipCord ,
				ProductionSituationJointing ,
				StandardOfTwisting ,
				MCCode ,
				Bobbin ,
				Cheese ,
				TaperBB ,
				ContainerOthers ,
				SpindleNo ,
				Quantity ,
				Polyester ,
				Nylon66 ,
				MaterialOthers ,
				YarnType ,
				Process ,
				Product ,
				Special ,
				Trial ,
				[Shift] ,
				ShiftName ,
				Remark ,
				Sender ,
				SenderTime ,
				Direct ,
				Relax ,
				Relax_k ,
				Relax_n ,
				Necessary ,
				NotNecessary ,
				SpecialMentionJointing ,
				SpecialMentionNoJointing ,
				TensileR1 ,
				TensileL1 ,
				TensileR2 ,
				TensileL2 ,
				TensileR3 ,
				TensileL3 ,
				TensileR4 ,
				TensileL4 ,
				TensileR5 ,
				TensileL5 ,
				TensileRSum ,
				TensileLSum ,
				FirstTwistingR1 ,
				FirstTwistingL1 ,
				FirstTwistingR2 ,
				FirstTwistingL2 ,
				FirstTwistingR3 ,
				FirstTwistingL3 ,
				FirstTwistingR4 ,
				FirstTwistingL4 ,
				FirstTwistingR5 ,
				FirstTwistingL5 ,
				FirstTwistingRSum ,
				FirstTwistingLSum ,
				SecondTwistingR1 ,
				SecondTwistingL1 ,
				SecondTwistingR2 ,
				SecondTwistingL2 ,
				SecondTwistingR3 ,
				SecondTwistingL3 ,
				SecondTwistingR4 ,
				SecondTwistingL4 ,
				SecondTwistingR5 ,
				SecondTwistingL5 ,
				SecondTwistingRSum ,
				SecondTwistingLSum ,
				Remark1 ,
				Remark2 ,
				Remark3 ,
				Remark4 ,
				Remark5 ,
				RemarkSum ,
				RemarkOther ,
			    Tester,
			    TesterTime,
			    TestResult
			)
			VALUES
			(
                @TwistYarn ,
				@CordDipping ,
				@Rawmaterial ,
				@SamplingDate ,
				@CustomerName ,
				@ProductCode ,
				@CordStructure ,
				@LotNo ,
				@ProductionSituationTwisting ,
				@ProductionSituationHeatSet ,
				@ProductionSituationDipCord ,
				@ProductionSituationJointing ,
				@StandardOfTwisting ,
				@MCCode ,
				@Bobbin ,
				@Cheese ,
				@TaperBB ,
				@ContainerOthers ,
				@SpindleNo ,
				@Quantity ,
				@Polyester ,
				@Nylon66 ,
				@MaterialOthers ,
				@YarnType ,
				@Process ,
				@Product ,
				@Special ,
				@Trial ,
				@Shift ,
				@ShiftName ,
				@Remark ,
				@Sender ,
				@SenderTime ,
				@Direct ,
				@Relax ,
				@Relax_k ,
				@Relax_n ,
				@Necessary ,
				@NotNecessary ,
				@SpecialMentionJointing ,
				@SpecialMentionNoJointing ,
				@TensileR1 ,
				@TensileL1 ,
				@TensileR2 ,
				@TensileL2 ,
				@TensileR3 ,
				@TensileL3 ,
				@TensileR4 ,
				@TensileL4 ,
				@TensileR5 ,
				@TensileL5 ,
				@TensileRSum ,
				@TensileLSum ,
				@FirstTwistingR1 ,
				@FirstTwistingL1 ,
				@FirstTwistingR2 ,
				@FirstTwistingL2 ,
				@FirstTwistingR3 ,
				@FirstTwistingL3 ,
				@FirstTwistingR4 ,
				@FirstTwistingL4 ,
				@FirstTwistingR5 ,
				@FirstTwistingL5 ,
				@FirstTwistingRSum ,
				@FirstTwistingLSum ,
				@SecondTwistingR1 ,
				@SecondTwistingL1 ,
				@SecondTwistingR2 ,
				@SecondTwistingL2 ,
				@SecondTwistingR3 ,
				@SecondTwistingL3 ,
				@SecondTwistingR4 ,
				@SecondTwistingL4 ,
				@SecondTwistingR5 ,
				@SecondTwistingL5 ,
				@SecondTwistingRSum ,
				@SecondTwistingLSum ,
				@Remark1 ,
				@Remark2 ,
				@Remark3 ,
				@Remark4 ,
				@Remark5 ,
				@RemarkSum ,
				@RemarkOther ,
			    @Tester,
			    @TesterTime,
			    @TestResult
			);

			SET @SamplingId = @@IDENTITY;
        END

        -- Update Error Status/Message
        SET @errNum = 0;
        SET @errMsg = 'Success';
	END TRY
	BEGIN CATCH
		SET @errNum = ERROR_NUMBER();
		SET @errMsg = ERROR_MESSAGE();
	END CATCH
END

GO
