/****** Object:  StoredProcedure [dbo].[SaveDIPProductionCondition]    Script Date: 20/10/2566 2:43:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author: Chumpon Asaneerat
-- Description:	SaveDIPProductionCondition
-- [== History ==]
-- <2022-08-20> :
--	- Stored Procedure Created.
--
-- [== Example ==]
--
-- 
-- =============================================
CREATE PROCEDURE [dbo].[SaveDIPProductionCondition] (
    @ProductCode nvarchar (30)  ,
	@S7CordStructure nvarchar (50)  ,
	@S7YarnType nvarchar (50)  ,
	@S71stTwist nvarchar (50)  ,
	@S72ndTwist nvarchar (50)  ,
	@S7ShapeOfYarn nvarchar (50)  ,
	@S7Weight decimal (18, 3)  ,
	@S7ProcessSettingTension nvarchar (50)  ,
	@S7UseTensor nvarchar (50)  ,
	@S7KnotCondition nvarchar (50)  ,
	@S7SuperNylonKnot nvarchar (50)  ,
	@S8DryeStretchSC bit   ,
	@S8DryeStretch decimal (18, 3)  ,
	@S8DryeStretchErr decimal (18, 3)  ,
	@S8DryeTempSC bit   ,
	@S8DryeTemp decimal (18, 3)  ,
	@S8DryeTempErr decimal (18, 3)  ,
	@S8DryePass decimal (18, 3)  ,
	@S8DryeTension nvarchar (50)  ,
	@S8HotStretchSC bit   ,
	@S8HotStretch decimal (18, 3)  ,
	@S8HotStretchErr decimal (18, 3)  ,
	@S8HotTempSC bit   ,
	@S8HotTemp decimal (18, 3)  ,
	@S8HotTempErr decimal (18, 3)  ,
	@S8HotPass decimal (18, 3)  ,
	@S8HotTension nvarchar (50)  ,
	@S8NormalStretchSC bit   ,
	@S8NormalStretch decimal (18, 3)  ,
	@S8NormalStretchErr decimal (18, 3)  ,
	@S8NormalTempSC bit   ,
	@S8NormalTemp decimal (18, 3)  ,
	@S8NormalTempErr decimal (18, 3)  ,
	@S8NormalPass decimal (18, 3)  ,
	@S8NormalTension nvarchar (50)  ,
	@S8TotalStretchSC bit   ,
	@S8TotalStretch decimal (18, 3)  ,
	@S8TotalStretchErr decimal (18, 3)  ,
	@S8TotalTempSC bit   ,
	@S8TotalTemp decimal (18, 3)  ,
	@S8TotalTempErr decimal (18, 3)  ,
	@S8TotalPass decimal (18, 3)  ,
	@S8TotalTension nvarchar (50)  ,
	@S8SpeedSC bit   ,
	@S8Speed decimal (18, 3)  ,
	@S8SpeedErr decimal (18, 3)  ,
	@S8NoOfCordsOfProcessing decimal (18, 3)  ,
	@S8NoOfCordsOfProcessingErr decimal (18, 3)  ,
	@S8Sofnor nvarchar (50)  ,
	@S8DrawNip nvarchar (50)  ,
	@S8Concentration nvarchar (50)  ,
	@S8NipRollerPressureNo1Front decimal (18, 3)  ,
	@S8NipRollerPressureNo1FrontErr decimal (18, 3)  ,
	@S8NipRollerPressureNo2Front decimal (18, 3)  ,
	@S8NipRollerPressureNo2FrontErr decimal (18, 3)  ,
	@S8NipRollerPressureNo1Back decimal (18, 3)  ,
	@S8NipRollerPressureNo1BackErr decimal (18, 3)  ,
	@S8NipRollerPressureNo2Back decimal (18, 3)  ,
	@S8NipRollerPressureNo2BackErr decimal (18, 3)  ,
	@S8WPUStandardNo1 decimal (18, 3)  ,
	@S8WPUStandardNo1Err decimal (18, 3)  ,
	@S8WPUStandardNo2 decimal (18, 3)  ,
	@S8WPUStandardNo2Err decimal (18, 3)  ,
	@S9ContactPressureUp bit   ,
	@S9ContactPressureDown bit   ,
	@S9ContactPressure nvarchar (50)  ,
	@S9BaseWindGear decimal (18, 3)  ,
	@S9TraverseGuideSizeLrage bit   ,
	@S9TraverseGuideSizeSmall bit   ,
	@S9TraverseGuideSize nvarchar (50)  ,
	@S9WindVoltageSet decimal (18, 3)  ,
	@S9WindVoltageSetErr decimal (18, 3)  ,
	@S9AyameDaial decimal (18, 6)  ,
	@S9AyameDaialErr decimal (18, 6)  ,
	@S9TensionSpringLrage bit   ,
	@S9TensionSpringSmall bit   ,
	@S9TensionSpring nvarchar (50)  ,
	@S9TensionWind nvarchar (50)  ,
	@S9PackingStandard decimal (18, 3)  ,
	@S9PackingStandardErr decimal (18, 3)  ,
	@S9TubeColor nvarchar (50)  ,
	@S9Tail nvarchar (50)  ,
	@S9CounterSetting decimal (18, 3)  ,
	@S9CounterSettingErr decimal (18, 3)  ,
	@S9CheeseWeight decimal (18, 3)  ,
	@S9CheeseWeightErr decimal (18, 3)  ,
	@S9HowToStartProductionEng nvarchar (100)  ,
	@S9HowToStartProductionTh nvarchar (100)  ,
	@S9Rewind nvarchar (100)  ,
	@S9Package nvarchar (100)  ,
	@S9Sampling nvarchar (100)  
, @errNum as int = 0 out
, @errMsg as nvarchar(MAX) = N'' out)
AS
BEGIN
	BEGIN TRY
        IF EXISTS (SELECT TOP 1 * FROM DIPProductionCondition WHERE ProductCode = @ProductCode)
        BEGIN
            UPDATE DIPProductionCondition 
               SET  S7CordStructure = @S7CordStructure ,
				S7YarnType = @S7YarnType ,
				S71stTwist = @S71stTwist ,
				S72ndTwist = @S72ndTwist ,
				S7ShapeOfYarn = @S7ShapeOfYarn ,
				S7Weight  = @S7Weight ,
				S7ProcessSettingTension = @S7ProcessSettingTension ,
				S7UseTensor = @S7UseTensor ,
				S7KnotCondition = @S7KnotCondition ,
				S7SuperNylonKnot = @S7SuperNylonKnot ,
				S8DryeStretchSC = @S8DryeStretchSC ,
				S8DryeStretch  = @S8DryeStretch ,
				S8DryeStretchErr  = @S8DryeStretchErr ,
				S8DryeTempSC = @S8DryeTempSC ,
				S8DryeTemp  = @S8DryeTemp ,
				S8DryeTempErr  = @S8DryeTempErr ,
				S8DryePass  = @S8DryePass ,
				S8DryeTension = @S8DryeTension ,
				S8HotStretchSC = @S8HotStretchSC ,
				S8HotStretch  = @S8HotStretch ,
				S8HotStretchErr  = @S8HotStretchErr ,
				S8HotTempSC = @S8HotTempSC ,
				S8HotTemp  = @S8HotTemp ,
				S8HotTempErr  = @S8HotTempErr ,
				S8HotPass  = @S8HotPass ,
				S8HotTension = @S8HotTension ,
				S8NormalStretchSC = @S8NormalStretchSC ,
				S8NormalStretch  = @S8NormalStretch ,
				S8NormalStretchErr  = @S8NormalStretchErr ,
				S8NormalTempSC = @S8NormalTempSC ,
				S8NormalTemp  = @S8NormalTemp ,
				S8NormalTempErr  = @S8NormalTempErr ,
				S8NormalPass  = @S8NormalPass ,
				S8NormalTension = @S8NormalTension ,
				S8TotalStretchSC = @S8TotalStretchSC ,
				S8TotalStretch  = @S8TotalStretch ,
				S8TotalStretchErr  = @S8TotalStretchErr ,
				S8TotalTempSC = @S8TotalTempSC ,
				S8TotalTemp  = @S8TotalTemp ,
				S8TotalTempErr  = @S8TotalTempErr ,
				S8TotalPass  = @S8TotalPass ,
				S8TotalTension = @S8TotalTension ,
				S8SpeedSC = @S8SpeedSC ,
				S8Speed  = @S8Speed ,
				S8SpeedErr  = @S8SpeedErr ,
				S8NoOfCordsOfProcessing  = @S8NoOfCordsOfProcessing ,
				S8NoOfCordsOfProcessingErr  = @S8NoOfCordsOfProcessingErr ,
				S8Sofnor = @S8Sofnor ,
				S8DrawNip = @S8DrawNip ,
				S8Concentration = @S8Concentration ,
				S8NipRollerPressureNo1Front  = @S8NipRollerPressureNo1Front ,
				S8NipRollerPressureNo1FrontErr  = @S8NipRollerPressureNo1FrontErr ,
				S8NipRollerPressureNo2Front  = @S8NipRollerPressureNo2Front ,
				S8NipRollerPressureNo2FrontErr  = @S8NipRollerPressureNo2FrontErr ,
				S8NipRollerPressureNo1Back  = @S8NipRollerPressureNo1Back ,
				S8NipRollerPressureNo1BackErr  = @S8NipRollerPressureNo1BackErr ,
				S8NipRollerPressureNo2Back  = @S8NipRollerPressureNo2Back ,
				S8NipRollerPressureNo2BackErr  = @S8NipRollerPressureNo2BackErr ,
				S8WPUStandardNo1  = @S8WPUStandardNo1 ,
				S8WPUStandardNo1Err  = @S8WPUStandardNo1Err ,
				S8WPUStandardNo2  = @S8WPUStandardNo2 ,
				S8WPUStandardNo2Err  = @S8WPUStandardNo2Err ,
				S9ContactPressureUp = @S9ContactPressureUp ,
				S9ContactPressureDown = @S9ContactPressureDown ,
				S9ContactPressure = @S9ContactPressure ,
				S9BaseWindGear  = @S9BaseWindGear ,
				S9TraverseGuideSizeLrage = @S9TraverseGuideSizeLrage ,
				S9TraverseGuideSizeSmall = @S9TraverseGuideSizeSmall ,
				S9TraverseGuideSize = @S9TraverseGuideSize ,
				S9WindVoltageSet  = @S9WindVoltageSet ,
				S9WindVoltageSetErr  = @S9WindVoltageSetErr ,
				S9AyameDaial  = @S9AyameDaial ,
				S9AyameDaialErr  = @S9AyameDaialErr ,
				S9TensionSpringLrage = @S9TensionSpringLrage ,
				S9TensionSpringSmall = @S9TensionSpringSmall ,
				S9TensionSpring = @S9TensionSpring ,
				S9TensionWind = @S9TensionWind ,
				S9PackingStandard  = @S9PackingStandard ,
				S9PackingStandardErr  = @S9PackingStandardErr ,
				S9TubeColor = @S9TubeColor ,
				S9Tail = @S9Tail ,
				S9CounterSetting  = @S9CounterSetting ,
				S9CounterSettingErr  = @S9CounterSettingErr ,
				S9CheeseWeight  = @S9CheeseWeight ,
				S9CheeseWeightErr  = @S9CheeseWeightErr ,
				S9HowToStartProductionEng = @S9HowToStartProductionEng ,
				S9HowToStartProductionTh = @S9HowToStartProductionTh ,
				S9Rewind = @S9Rewind ,
				S9Package = @S9Package ,
				S9Sampling = @S9Sampling 
             WHERE ProductCode = @ProductCode
        END
        ELSE
        BEGIN
			INSERT INTO DIPProductionCondition
		    (
				ProductCode  ,
				S7CordStructure ,
				S7YarnType ,
				S71stTwist ,
				S72ndTwist ,
				S7ShapeOfYarn ,
				S7Weight  ,
				S7ProcessSettingTension ,
				S7UseTensor ,
				S7KnotCondition ,
				S7SuperNylonKnot ,
				S8DryeStretchSC ,
				S8DryeStretch  ,
				S8DryeStretchErr  ,
				S8DryeTempSC ,
				S8DryeTemp  ,
				S8DryeTempErr  ,
				S8DryePass  ,
				S8DryeTension ,
				S8HotStretchSC ,
				S8HotStretch  ,
				S8HotStretchErr  ,
				S8HotTempSC ,
				S8HotTemp  ,
				S8HotTempErr  ,
				S8HotPass  ,
				S8HotTension ,
				S8NormalStretchSC ,
				S8NormalStretch  ,
				S8NormalStretchErr  ,
				S8NormalTempSC ,
				S8NormalTemp  ,
				S8NormalTempErr  ,
				S8NormalPass  ,
				S8NormalTension ,
				S8TotalStretchSC ,
				S8TotalStretch  ,
				S8TotalStretchErr  ,
				S8TotalTempSC ,
				S8TotalTemp  ,
				S8TotalTempErr  ,
				S8TotalPass  ,
				S8TotalTension ,
				S8SpeedSC ,
				S8Speed  ,
				S8SpeedErr  ,
				S8NoOfCordsOfProcessing  ,
				S8NoOfCordsOfProcessingErr  ,
				S8Sofnor ,
				S8DrawNip ,
				S8Concentration ,
				S8NipRollerPressureNo1Front  ,
				S8NipRollerPressureNo1FrontErr  ,
				S8NipRollerPressureNo2Front  ,
				S8NipRollerPressureNo2FrontErr  ,
				S8NipRollerPressureNo1Back  ,
				S8NipRollerPressureNo1BackErr  ,
				S8NipRollerPressureNo2Back  ,
				S8NipRollerPressureNo2BackErr  ,
				S8WPUStandardNo1  ,
				S8WPUStandardNo1Err  ,
				S8WPUStandardNo2  ,
				S8WPUStandardNo2Err  ,
				S9ContactPressureUp ,
				S9ContactPressureDown ,
				S9ContactPressure ,
				S9BaseWindGear  ,
				S9TraverseGuideSizeLrage ,
				S9TraverseGuideSizeSmall ,
				S9TraverseGuideSize ,
				S9WindVoltageSet  ,
				S9WindVoltageSetErr  ,
				S9AyameDaial  ,
				S9AyameDaialErr  ,
				S9TensionSpringLrage ,
				S9TensionSpringSmall ,
				S9TensionSpring ,
				S9TensionWind ,
				S9PackingStandard  ,
				S9PackingStandardErr  ,
				S9TubeColor ,
				S9Tail ,
				S9CounterSetting  ,
				S9CounterSettingErr  ,
				S9CheeseWeight  ,
				S9CheeseWeightErr  ,
				S9HowToStartProductionEng ,
				S9HowToStartProductionTh ,
				S9Rewind ,
				S9Package ,
				S9Sampling 
			)
			VALUES
			(
                @ProductCode  ,
				@S7CordStructure ,
				@S7YarnType ,
				@S71stTwist ,
				@S72ndTwist ,
				@S7ShapeOfYarn ,
				@S7Weight  ,
				@S7ProcessSettingTension ,
				@S7UseTensor ,
				@S7KnotCondition ,
				@S7SuperNylonKnot ,
				@S8DryeStretchSC ,
				@S8DryeStretch  ,
				@S8DryeStretchErr  ,
				@S8DryeTempSC ,
				@S8DryeTemp  ,
				@S8DryeTempErr  ,
				@S8DryePass  ,
				@S8DryeTension ,
				@S8HotStretchSC ,
				@S8HotStretch  ,
				@S8HotStretchErr  ,
				@S8HotTempSC ,
				@S8HotTemp  ,
				@S8HotTempErr  ,
				@S8HotPass  ,
				@S8HotTension ,
				@S8NormalStretchSC ,
				@S8NormalStretch  ,
				@S8NormalStretchErr  ,
				@S8NormalTempSC ,
				@S8NormalTemp  ,
				@S8NormalTempErr  ,
				@S8NormalPass  ,
				@S8NormalTension ,
				@S8TotalStretchSC ,
				@S8TotalStretch  ,
				@S8TotalStretchErr  ,
				@S8TotalTempSC ,
				@S8TotalTemp  ,
				@S8TotalTempErr  ,
				@S8TotalPass  ,
				@S8TotalTension ,
				@S8SpeedSC ,
				@S8Speed  ,
				@S8SpeedErr  ,
				@S8NoOfCordsOfProcessing  ,
				@S8NoOfCordsOfProcessingErr  ,
				@S8Sofnor ,
				@S8DrawNip ,
				@S8Concentration ,
				@S8NipRollerPressureNo1Front  ,
				@S8NipRollerPressureNo1FrontErr  ,
				@S8NipRollerPressureNo2Front  ,
				@S8NipRollerPressureNo2FrontErr  ,
				@S8NipRollerPressureNo1Back  ,
				@S8NipRollerPressureNo1BackErr  ,
				@S8NipRollerPressureNo2Back  ,
				@S8NipRollerPressureNo2BackErr  ,
				@S8WPUStandardNo1  ,
				@S8WPUStandardNo1Err  ,
				@S8WPUStandardNo2  ,
				@S8WPUStandardNo2Err  ,
				@S9ContactPressureUp ,
				@S9ContactPressureDown ,
				@S9ContactPressure ,
				@S9BaseWindGear  ,
				@S9TraverseGuideSizeLrage ,
				@S9TraverseGuideSizeSmall ,
				@S9TraverseGuideSize ,
				@S9WindVoltageSet  ,
				@S9WindVoltageSetErr  ,
				@S9AyameDaial  ,
				@S9AyameDaialErr  ,
				@S9TensionSpringLrage ,
				@S9TensionSpringSmall ,
				@S9TensionSpring ,
				@S9TensionWind ,
				@S9PackingStandard  ,
				@S9PackingStandardErr  ,
				@S9TubeColor ,
				@S9Tail ,
				@S9CounterSetting  ,
				@S9CounterSettingErr  ,
				@S9CheeseWeight  ,
				@S9CheeseWeightErr  ,
				@S9HowToStartProductionEng ,
				@S9HowToStartProductionTh ,
				@S9Rewind ,
				@S9Package ,
				@S9Sampling 
			);
        END

        -- Update Error Status/Message
        SET @errNum = 0;
        SET @errMsg = 'Success';
	END TRY
	BEGIN CATCH
		SET @errNum = ERROR_NUMBER();
		SET @errMsg = ERROR_MESSAGE();
	END CATCH
END

GO
